#!/usr/bin/env bash
set -e

# Enter the default network interface here to get the
# IP address from.
default_interface=eth0

if [ $# -eq 0 ]
then
    interface=$default_interface
else
    interface=$1
fi

regex="inet ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})"

if [[ $(ifconfig $interface) =~ $regex ]]
then
    echo "${BASH_REMATCH[1]}"
fi
